[package]
name = "minimal-web-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
rand = "0.8.5"
sha2 = "0.10.2"
chrono = "0.4.22"